name:                uKanren-spec
version:             0.1.0.0
github:              "RehMaar/uKanren-spec"
license:             BSD3
author:              "Maria Kuklina"
maintainer:          "kuklina.md@gmail.com"
copyright:           "2019 Karia Kuklina"

extra-source-files:
- README.md


dependencies:
- base >= 4.7 && < 5
- containers
- process 
- temporary 
- text 
- fgl
- graphviz 
- mtl
- extra
- directory
- timeit
- random

library:
  source-dirs: 
  - src/
  - src/old_programs/
  - src/new_programs/
  - src/utils

executables:
  uks-exe:
    main:                Main.hs
    source-dirs:         
    - app
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uKanren-spec

tests:
  uks-test:
    main:                Test.hs
    source-dirs:         
    - test/
    - test/test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uKanren-spec
